[package]
name = "tracy-client"
version = "0.16.4" # AUTO-BUMP
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.mkd"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/tracy-client"
description = """
High level bindings to the client libraries for the Tracy profiler
"""

[[test]]
name = "tests"
path = "tests/tests.rs"
harness = false

[[test]]
name = "loom"
path = "tests/loom.rs"
harness = false

[[bench]]
name = "client"
path = "benches/client.rs"
harness = false

[dev-dependencies]
criterion = "0.3"

[dependencies]
once_cell = "1.10"

[dependencies.sys]
path = "../tracy-client-sys"
package = "tracy-client-sys"
version = ">=0.21.2, <0.23.0" # AUTO-UPDATE
default-features = false
features = ["manual-lifetime", "delayed-init"]

[target.'cfg(loom)'.dependencies.loom]
version = "0.5"

[features]
# Refer to FEATURES.mkd for documentation on features.
default = [ "enable", "system-tracing", "context-switch-tracing", "sampling", "code-transfer",
            "broadcast", "callstack-inlines" ]
broadcast = ["sys/broadcast"]
code-transfer = ["sys/code-transfer"]
context-switch-tracing = ["sys/context-switch-tracing"]
enable = ["sys/enable"]
fibers = ["sys/fibers"]
timer-fallback = ["sys/timer-fallback"]
ondemand = ["sys/ondemand"]
only-ipv4 = ["sys/only-ipv4"]
only-localhost = ["sys/only-localhost"]
sampling = ["sys/sampling"]
system-tracing = ["sys/system-tracing"]
callstack-inlines = ["sys/callstack-inlines"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "tracy_client_docs"]
