name: Test tracy-client

on:
  push:
    paths:
    - 'tracy-client/**'
    - '.github/workflows/tracy-client.yml'
    - '!tracy-client/**.mkd'
    - '!tracy-client/LICENSE-*'
  pull_request:
    types: [opened, repoened, synchronize]

jobs:
  native-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain: [nightly, stable, 1.40.0]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        flags: ["", "--release", "--no-default-features", "--features ci-all-features"]
        include:
          - rust_toolchain: nightly
            os: ubuntu-latest
            flags: "--features static_span"
    timeout-minutes: 20
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
            submodules: 'recursive'
      - name: Install Rust ${{ matrix.rust_toolchain }}
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust_toolchain }}
            profile: minimal
            default: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=tracy-client/Cargo.toml ${{ matrix.flags }} -- --nocapture
        env:
          TRACY_NO_INVARIANT_CHECK: 1
